---
# tasks file for packages
    - name: Install serveral packages
      yum:
         state: present
         name: '{{ item }}'
      loop:
            - net-tools
            - ntp
            - ntpdate
            - vsftpd
            - net-snmp
            - net-snmp-utils
            - sysfsutils
            - telnet
            - tcpdump

            - psmisc
            - unzip
    